language: ruby

before_install:
  - gem update --system
  - gem install bundler

services:
  - postgresql

before_script:
  - psql -c 'create database "makers_bnb_test";' -U postgres || true


script:
  - RACK_ENV=test bundle exec rake --trace rubocop db:auto_migrate

# bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

env:
    - DATABASE=postgresql

notifications:
  email: false
