language: ruby

services:
  - postgresql

before_script:
  - psql -c 'create database "makers_bnb_test";' -U postgres || true
  
script:
  - RACK_ENV=test bundle exec rake --trace rubocop db:auto_migrate
  
before_install:
 - sudo apt-get install -y postgresql-server-dev-9.2

notifications:
  email: false
